@baseUrl = https://localhost:7035
@id = "{{$guid}}"
// random string

POST {{baseUrl}}/categories
Accept: application/json
X-Api-Version: 1
Content-Type: application/json

{
  "title": "Salary",
  "description": "Salary",
  "categoryType": "Income",
  "parentId": null
}

###

GET {{baseUrl}}/categories/daac02c8-acf9-499a-813c-f98df96f945d
Accept: application/json
X-Api-Version: 1
Content-Type: application/json

###

PUT {{baseUrl}}/categories/daac02c8-acf9-499a-813c-f98df96f945d
Accept: application/json
X-Api-Version: 1
Content-Type: application/json

{
  "title": "Salary",
  "description": "",
  "categoryType": "Income",
  "parentId": "daac02c8-acf9-499a-813c-f98df96f945d"
}

###
